added controls on requirements

diff --git a/dynmotd b/dynmotd
--- a/dynmotd
+++ b/dynmotd
@@ -5,13 +5,20 @@ has() {
 	type -p "$1" >/dev/null 
 }
 
+needs_commands="curl awk xargs basename tr grep lscpu free ps pgrep cut uptime df"
+for cmd in $needs_commands
+do
+	if ! type -p "$cmd" > /dev/null
+	then
+		printf "%-30s \n" "Command not found: $cmd"
+		command_not_found=true
+	fi
+done
+
+[[ -z $command_not_found ]] || exit 2
+
 HOSTNAME=$(hostname -s)
 IP=$(hostname -I | awk '{print $1}')
-
-#EXT_IP=$(curl -s ipinfo.io/ip)
-#EXT_IP=${EXT_IP:-None}
-
-#IP=$(getent hosts $(hostname -s) | awk '{print $1}')
 KERNEL=$(uname -r)
 
 #OS distro
@@ -31,8 +38,8 @@ fi
 CPU_COUNT=$(LANG=en.UTF-8 lscpu | grep ^'CPU(s)' | awk -F ': ' '{print $2}' | xargs)
 CPU_VENDOR=$(LANG=en.UTF-8 lscpu | grep ^'Vendor ID' | awk -F ': ' '{print $2}' | xargs)
 CPU_MODEL=$(LANG=en.UTF-8 lscpu | grep ^'Model name' | awk -F ': ' '{print $2}' | xargs)
-MEMORY=$(free -h --giga | grep "Mem" | awk '{print $2,"-",$3,"-",$4}')
-SWAP=$(free -h --giga | grep "Swap" | awk '{print $2,"-",$3,"-",$4}')
+MEMORY=$(LANG=en.UTF-8 free -h --giga | grep "Mem" | awk '{print $2,"-",$3,"-",$4}')
+SWAP=$(LANG=en.UTF-8 free -h --giga | grep "Swap" | awk '{print $2,"-",$3,"-",$4}')
 PSA=$(ps -Afl | wc -l)
 ZOMBIE=$(pgrep defunct | wc -l)
 
